tempo_max = 150;
flag_plotEL = true;
flag_plotPD = true;
flag_plotPK = true;
flag_const_res = false;
dose = 3;
intervalo = 6;
flag_intervalo_const = true;
const_resistencia = 0;
EL(tempo_max, flag_plotEL, flag_plotPD, flag_plotPK, dose, intervalo, flag_intervalo_const, const_resistencia, flag_const_res);
